export const FETCHING_LISTINGS = 'FETCHING_LISTINGS'
export const FAIL_FETCH_LISTINGS = 'FAIL_FETCH_LISTINGS'
export const FETCH_LISTINGS = 'FETCH_LISTINGS'

export const FETCH_LISTING = 'FETCH_LISTING'
export const FETCHING_LISTING = 'FETCHING_LISTING'
export const FAIL_FETCH_LISTING = 'FAIL_FETCH_LISTING'


export const RENDERLOGINFORM = 'RENDERLOGINFORM'


